local GLOBAL = {}

GLOBAL.lspDir = vim.fn.stdpath("data").."/mason/bin"

GLOBAL.modes = {
  ["n"] = { name = "NORMAL", highlight = "CK_NormalMode" , icon = "𝓝"},
  ["niI"] = { name = "NORMAL i", highlight = "CK_NormalMode", icon = "𝓝"},
  ["niR"] = { name = "NORMAL r", highlight = "CK_NormalMode", icon = "𝓝"},
  ["niV"] = { name = "NORMAL v", highlight = "CK_NormalMode", icon = "𝓝"},
  ["no"] = { name = "N-PENDING", highlight = "CK_NormalMode", icon = "𝓝"},
  ["i"] = { name = "INSERT", highlight = "CK_InsertMode", icon = "𝓘"},
  ["ic"] = { name = "INSERT (completion)", highlight = "CK_InsertMode", icon = "𝓘"},
  ["ix"] = { name = "INSERT completion", highlight = "CK_InsertMode", icon = "𝓘"},
  ["t"] = { name = "TERMINAL", highlight = "CK_TerminalMode", icon = "𝓣"},
  ["nt"] = { name = "NTERMINAL", highlight = "CK_NTerminalMode", icon = "𝓝𝓣"},
  ["v"] = { name = "VISUAL", highlight = "CK_VisualMode", icon = "𝓥"},
  ["V"] = { name = "V-LINE", highlight = "CK_VisualMode", icon = "𝓥"},
  ["Vs"] = { name = "V-LINE (Ctrl O)", highlight = "CK_VisualMode", icon = "𝓥"},
  [""] = { name = "V-BLOCK", highlight = "CK_VisualMode", icon = "𝓥"},
  ["R"] = { name = "REPLACE", highlight = "CK_ReplaceMode", icon = "𝓡"},
  ["Rv"] = { name = "V-REPLACE", highlight = "CK_ReplaceMode", icon = "𝓡"},
  ["s"] = { name = "SELECT", highlight = "CK_SelectMode", icon = "𝓢"},
  ["S"] = { name = "S-LINE", highlight = "CK_SelectMode", icon = "𝓢"},
  [""] = { name = "S-BLOCK", highlight = "CK_SelectMode", icon = "𝓢"},
  ["c"] = { name = "COMMAND", highlight = "CK_CommandMode", icon = "𝓒"},
  ["cv"] = { name = "COMMAND", highlight = "CK_CommandMode", icon = "𝓒"},
  ["ce"] = { name = "COMMAND", highlight = "CK_CommandMode", icon = "𝓒"},
  ["r"] = { name = "PROMPT", highlight = "CK_ConfirmMode", icon = "𝓒"},
  ["rm"] = { name = "MORE", highlight = "CK_ConfirmMode", icon = "𝓒"},
  ["r?"] = { name = "CONFIRM", highlight = "CK_ConfirmMode", icon = "𝓒"},
  ["!"] = { name = "SHELL", highlight = "CK_TerminalMode", icon = "𝓣"},
}

GLOBAL.colors = {
  none = "NONE",
  bg_dark = "#1f2335",
  bg = "#24283b",
  bg_highlight = "#292e42",
  terminal_black = "#414868",
  fg = "#c0caf5",
  fg_dark = "#a9b1d6",
  fg_gutter = "#3b4261",
  dark3 = "#545c7e",
  comment = "#565f89",
  dark5 = "#737aa2",
  blue0 = "#3d59a1",
  blue = "#7aa2f7",
  cyan = "#7dcfff",
  blue1 = "#2ac3de",
  blue2 = "#0db9d7",
  blue5 = "#89ddff",
  blue6 = "#b4f9f8",
  blue7 = "#394b70",
  magenta = "#bb9af7",
  magenta2 = "#ff007c",
  purple = "#9d7cd8",
  orange = "#ff9e64",
  yellow = "#e0af68",
  green = "#9ece6a",
  green1 = "#73daca",
  green2 = "#41a6b5",
  teal = "#1abc9c",
  red = "#f7768e",
  red1 = "#db4b4b",
  git = { change = "#6183bb", add = "#449dab", delete = "#914c54" },
  gitSigns = {
    add = "#266d6a",
    change = "#536c9e",
    delete = "#b2555b",
  },
}

GLOBAL.separators = {
  left = "", right = "",
}

GLOBAL.kindIcons = {
  Text          = "",
  Method        = "",
  Function      = "",
  Constructor   = "",
  Field         = "",
  Variable      = "",
  Class         = "ﴯ",
  Interface     = "",
  Module        = "",
  Property      = "ﰠ",
  Unit          = "",
  Value         = "",
  Enum          = "",
  Keyword       = "",
  Snippet       = "",
  Color         = "",
  File          = "",
  Reference     = "",
  Folder        = "",
  EnumMember    = "",
  Constant      = "",
  Struct        = "",
  Event         = "",
  Operator      = "",
  TypeParameter = ""
}

return GLOBAL
